name: manage-azure-policy-a1a8454b
on:
  push:
    paths:
      - 'initiatives/test_initiative_48de3489-c333-4bcc-ad07-28ab705481eb/**'
      - .github/workflows/manage-azure-policy-a1a8454b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a1a8454b}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/test_initiative_48de3489-c333-4bcc-ad07-28ab705481eb/**
